### ISSUE TITLE
问下作者有分页计划吗？

### ISSUE THREAD

**Issue by qxlqaq** [zowiegong/hexo-theme-os#2]
挺不错简洁的小主题，有点镜像站的风格，哈哈请问作者有分页的计划吗😁？

**Comment by WayneGongCN** [comment]
没有分页功能其实是因为我太懒了 :sweat_smile:

喜欢的话很乐意加上 😄

**Comment by WayneGongCN** [comment]
为首页加上了一个简陋的分页

通过站点配置文件控制
