### ISSUE TITLE
分页路径问题

### ISSUE THREAD

**Issue by AutismSuperman** [zowiegong/hexo-theme-os#6]
目前分页的相对路径 如
`page/2`  应该为 `/`

**Comment by WayneGongCN** [comment]
这里确实有问题。

由于我在调试的时候在站点的配置里设置了 `index_generator.path = /` 没有发现这个问题，
虽然我也不知道 `index_generator.path` 与 `root` 这两个配置有什么区别。

**Comment by WayneGongCN** [comment]
也许这个问题被修复了
